# Generated by Django 5.2.8 on 2025-11-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('engagement', 'Engagement'), ('corporate', 'Corporate Event'), ('concert', 'Concert'), ('festival', 'Festival'), ('baby_shower', 'Baby Shower'), ('private_party', 'Private Party')], max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
